import { styled, keyframes } from '@stitches/react';

const floating = keyframes({
  from: {
    transform: 'translateY(10px)',
  },
  to: {
    transform: 'translateY(-10px)',
  },
});

const animateSvgStroke1 = keyframes({
  '0%': {
    strokeDashoffset: '1951.7640380859375px',
    strokeDasharray: '1951.7640380859375px',
  },

  '100%': {
    strokeDashoffset: 0,
    strokeDasharray: '1951.7640380859375px',
  },
});

const animateSvgFill1 = keyframes({
  '0%': {
    fill: 'transparent',
  },

  '100%': {
    fill: 'rgb(47, 47, 47)',
  },
});

const animateSvgStroke2 = keyframes({
  '0%': {
    strokeDashoffset: '1951.572021484375px',
    strokeDasharray: '1951.572021484375px',
  },

  '100%': {
    strokeDashoffset: 0,
    strokeDasharray: '1951.572021484375px',
  },
});

const animateSvgFill2 = keyframes({
  '0%': {
    fill: 'transparent',
  },

  '100%': {
    fill: 'rgb(47, 47, 47)',
  },
});

/***************************************************
  
 * Generated by SVG Artista on 12/24/2021, 8:18:46 PM
 * MIT license (https://opensource.org/licenses/MIT)
 * W. https://svgartista.net

 **************************************************/
export const LogoStyles = styled('div', {
  animation: `${floating} 1s infinite alternate`,
  width: 400,
  height: 400,
  filter: 'drop-shadow(0 0 10px rgba(0, 0, 0,0.4))',

  'path:nth-child(1)': {
    fill: '$logoLeft',
  },

  'path:nth-child(2)': {
    fill: '$logoRight',
  },

  '@media (max-width: 992px)': {
    width: 200,
    height: 200,
  },
  '.logo-animation-1': {
    opacity: 0.8,
    webkitAnimation: `${animateSvgStroke1} 3s ease 0s both, ${animateSvgFill1} 3s ease 0.8s both`,
    animation: `${animateSvgStroke1} 3s ease 0s both, ${animateSvgFill1} 3s ease 0.8s both`,
  },

  '.logo-animation-2': {
    webkitanimation: `${animateSvgStroke2} 3s ease 0.12s both, ${animateSvgFill2} 3s ease 0.9s both`,
    animation: `${animateSvgStroke2} 3s ease 0.12s both, ${animateSvgFill2} 3s ease 0.9s both`,
  },
});
