import { styled } from '@stitches/react';

export const LogoStyles = styled('div', {
  width: '400px',
  height: '400px',

  '@media (max-width: 992px)': {
    width: '200px',
    height: '200px',
  },

  /***************************************************
  
 * Generated by SVG Artista on 12/24/2021, 8:18:46 PM
 * MIT license (https://opensource.org/licenses/MIT)
 * W. https://svgartista.net

 **************************************************/

  '@-webkit-keyframes animate-svg-stroke-1': {
    '0%': {
      strokeDashoffset: '1951.7640380859375px',
      strokeDasharray: '1951.7640380859375px',
    },

    '100%': {
      strokeDashoffset: 0,
      strokeDasharray: '1951.7640380859375px',
    },
  },

  '@keyframes animate-svg-stroke-1': {
    '0%': {
      strokeDashoffset: '1951.7640380859375px',
      strokeDasharray: '1951.7640380859375px',
    },

    '100%': {
      strokeDashoffset: 0,
      strokeDasharray: '1951.7640380859375px',
    },
  },

  '@-webkit-keyframes animate-svg-fill-1': {
    '0%': {
      fill: 'transparent',
    },

    '100%': {
      fill: 'rgb(47, 47, 47)',
    },
  },

  '@keyframes animate-svg-fill-1': {
    '0%': {
      fill: 'transparent',
    },

    '100%': {
      fill: 'rgb(47, 47, 47)',
    },
  },

  '.logo-animation-1': {
    webkitAnimation:
      'animate-svg-stroke-1 3s ease 0s both, animate-svg-fill-1 3s ease 0.8s both',
    animation:
      'animate-svg-stroke-1 3s ease 0s both,animate-svg-fill-1 3s ease 0.8s both',
  },

  '@-webkit-keyframes animate-svg-stroke-2': {
    '0%': {
      strokeDashoffset: '1951.572021484375px',
      strokeDasharray: '1951.572021484375px',
    },

    '100%': {
      strokeDashoffset: 0,
      strokeDasharray: '1951.572021484375px',
    },
  },

  '@keyframes animate-svg-stroke-2': {
    '0%': {
      strokeDashoffset: '1951.572021484375px',
      strokeDasharray: '1951.572021484375px',
    },

    '100%': {
      strokeDashoffset: 0,
      strokeDasharray: '1951.572021484375px',
    },
  },

  '@-webkit-keyframes animate-svg-fill-2': {
    '0%': {
      fill: 'transparent',
    },

    '100%': {
      fill: 'rgb(47, 47, 47)',
    },
  },

  '@keyframes animate-svg-fill-2': {
    '0%': {
      fill: 'transparent',
    },

    '100%': {
      fill: 'rgb(47, 47, 47)',
    },
  },

  '.logo-animation-2': {
    webkitanimation:
      'animate-svg-stroke-2 3s ease 0.12s both, animate-svg-fill-2 3s ease 0.9s both',
    animation:
      'animate-svg-stroke-2 3s ease 0.12s both, animate-svg-fill-2 3s ease 0.9s both',
  },
});
