import { theme } from 'stitches.config';
import Head from 'next/head';
import Main from 'src/components/Sections/Main';

export default function Home() {
  return (
    <div>
      <Head>
        <title>José Victor - Front-end developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="shortcut icon" href="/images/favicon.ico" />
      </Head>
      <Main />
    </div>
  );
}
