import { theme } from 'stitches.config';
import Head from 'next/head';
import Main from 'src/components/Sections/Main';
import About from 'src/components/Sections/About';
import Works from 'src/components/Sections/Works';
import Skills from 'src/components/Sections/Skills';
import Contact from 'src/components/Sections/Contact';
import React from 'react';

export default function Home() {
  return (
    <div>
      <Head>
        <title>José Victor - Front-end developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="shortcut icon" href="/images/favicon.ico" />
      </Head>
      <Main />
      <About />
      <Works />
      <Skills />
      <Contact />
    </div>
  );
}
