import { theme } from 'stitches.config';
import Head from 'next/head';
import { Navbar } from 'components/Navbar';

export default function Home() {
  return (
    <div>
      <Head>
        <title>José Victor - Front-end developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
    </div>
  );
}
